// Generated by CoffeeScript 1.3.3

define(["underscore"], function(_) {
  var Chain;
  return Chain = (function() {

    function Chain(stones, liberties) {
      this.stones = stones;
      this.liberties = liberties;
    }

    Chain.prototype.get_liberties = function() {
      return this.liberties;
    };

    Chain.prototype.in_atari = function() {
      return _.size(this.liberties) === 1;
    };

    Chain.prototype.get_stones = function() {
      return this.stones;
    };

    return Chain;

  })();
});
