// Generated by CoffeeScript 1.3.3

(function(global) {
  var _GoBoard;
  _GoBoard = (function() {

    _GoBoard.VERSION = '0.1';

    function _GoBoard(container, container_size, board_size) {
      this.container = container;
      this.container_size = container_size;
      this.board_size = board_size;
      requirejs.config({
        baseUrl: "scripts",
        urlArgs: "bust=" + (new Date()).getTime(),
        paths: {
          "domReady": "helper/domReady"
        },
        shim: {
          "app": {
            exports: "_GoBoard"
          }
        }
      });
      setTimeout((function() {
        return require(["app"], function(_GoBoard) {
          var lol;
          lol = new _GoBoard(container, container_size, board_size);
        });
      }), 0);
      return;
    }

    return _GoBoard;

  })();
  if (global.GoBoard) {
    throw new Error("GoBoard has already been defined");
  } else {
    global.GoBoard = _GoBoard;
  }
})(this || (1, eval_)("this"));
