// Generated by CoffeeScript 1.6.3
var assert, chai, expect, should;

chai = require('chai');

assert = chai.assert;

should = chai.should();

expect = chai.expect;

describe('Testing "Other"', function(done) {
  beforeEach(function(done) {
    var requirejs;
    requirejs = require('requirejs');
    return requirejs(["config", "main"], function(config, goban) {
      return done();
    });
  });
  describe("#1 Other Suite:", function() {
    return it("Other.test", function() {
      var foo;
      foo = 'lol';
      return expect(foo).to.be.a('string');
    });
  });
  return describe("#2 Boo Suite:", function() {
    return it("Boo.test", function() {
      var foo;
      foo = 5;
      return expect(foo).to.be.a('string');
    });
  });
});
