// Generated by CoffeeScript 1.3.3

define("Chain", function() {
  var Chain;
  return Chain = (function() {

    function Chain() {
      alert("lol");
    }

    Chain.prototype.move = function() {
      return alert("rawr");
    };

    return Chain;

  })();
});
