// Generated by CoffeeScript 1.4.0

define(function(require) {
  var BoardState, murmurhash3;
  murmurhash3 = require('murmurhash3');
  BoardState = (function() {
    /*
        board state:
            move_color (who made the move in the board state)
                @BLACK or @WHITE
            stones_added:
                {WHITE:[collection of coords], BLACK:[collection of coords]}
    
            stones_removed:
                {WHITE:[collection of coords], BLACK:[collection of coords]}
    */

    function BoardState(board_state, move_color) {
      this.board_state = board_state;
      this.move_color = move_color;
      return this;
    }

    BoardState.prototype.getBoardState = function() {
      return this.board_state;
    };

    BoardState.prototype.getWhoMoved = function() {
      return this.move_color;
    };

    BoardState.prototype.getHash = function() {
      var virtual_board_string;
      virtual_board_string = this.board_state.toString().concat(this.move_color.toString());
      return murmurhash3.murmurhash3_32_gc(virtual_board_string, 1);
    };

    return BoardState;

  })();
  return BoardState;
});
