// Generated by CoffeeScript 1.4.0

(function(global) {
  var _GoBoard;
  _GoBoard = (function() {

    function _GoBoard(container, container_size, board_size) {
      var get_this;
      this.container = container;
      this.container_size = container_size;
      this.board_size = board_size;
      requirejs.config({
        urlArgs: "bust=" + (new Date()).getTime(),
        shim: {
          "app": {
            exports: "_GoBoard"
          }
        }
      });
      get_this = this;
      require(["app"], function(_GoBoard) {
        return get_this.go_board = new _GoBoard(container, container_size, board_size);
      });
    }

    return _GoBoard;

  })();
  if (global.GoBoard) {
    throw new Error("GoBoard has already been defined");
  } else {
    global.GoBoard = _GoBoard;
  }
})(this || (1, eval_)("this"));
