// Generated by CoffeeScript 1.6.3
var Mocha, mocha, requirejs;

requirejs = require('requirejs');

Mocha = require('mocha');

mocha = new Mocha;

mocha.reporter('spec').ui('bdd');

mocha.addFile('spec/goban.js');

mocha.run(function(failures) {
  return process.on("exit", function() {
    return process.exit(failures);
  });
});
